#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history

# vim as default
export EDITOR="vim"


export HOMEBREW_CASK_OPTS="--appdir=/Applications"

HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH=$HOME/.fnm:$PATH
export PATH=/opt/homebrew/bin:$PATH

eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"




